name: GITHUB_TAG

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Extract Tag
          id: extract_tag
#          run: echo ::set-output name=tag::$(git describe --tags `git rev-list --tags --max-count=1`)
#          run: echo "tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $LATEST_TAG
          run: echo "tag=value" >> $LATEST_TAG

        - name: Show Tag
          run: echo $LATEST_TAG
