name: GITHUB_TAG

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
    build:
        runs-on: ubuntu-latest
        env:
          Latest_Tag: "latest"
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Extract Tag
          id: extract_tag
#          run: echo ::set-output name=tag::$(git describe --tags `git rev-list --tags --max-count=1`)
          run: echo "tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $Latest_Tag

        - name: Show Tag
          run: echo $Latest_Tag
